spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-manager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: /7L+BZBj0TcqzJDo4KB81Za3h748Z+WeFw4x+DXyzhw=
  expiration: 86400000