spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  springdoc:
    default-produces-media-type: application/json
  server:
    servlet:
      context-path: /api/v1/



jwt:
  secret: /7L+BZBj0TcqzJDo4KB81Za3h748Z+WeFw4x+DXyzhw=
  expiration: 86400000